# -----------------------------------------------
# Customization of the qemuarm machine configuration
# -----------------------------------------------

require conf/machine/qemuarm.conf
MACHINEOVERRIDES =. "qemuarm:"

# -----------------------------------------------
# Machine specific configuration
# -----------------------------------------------

DISTRO_FEATURES:append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""

# Memory and partition table properties
STORAGE_TYPE = "vda"
PTABLE_TYPE = "gpt"

# Bootloader settings
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
# Use the generic implementation and not the one shipped with u-boot (declared as demo)
PREFERRED_RPROVIDER_u-boot-default-env = "libubootenv"

# Inspiration for the following configuration taken from: 
# https://ejaaskel.dev/yocto-emulation-setting-up-qemu-with-u-boot/

# Set the required entrypoint and loadaddress
# These are usually 00008000 for Arm machines
UBOOT_ENTRYPOINT =       "0x00008000"
UBOOT_LOADADDRESS =      "0x00008000"

# Set kernel loaddaddr, should match the one u-boot uses
KERNEL_EXTRA_ARGS += "LOADADDR=${UBOOT_ENTRYPOINT}"

#IMAGE_BOOT_FILES = "u-boot.bin boot.scr u-boot-initial-env"
IMAGE_BOOT_FILES = "zImage qemuarm.dtb"

# -----------------------------------------------
# runqemu configuration
# -----------------------------------------------

QB_ROOTFS_OPT = "-drive id=disk0,file=@ROOTFS@,if=none,format=qcow2 -device virtio-blk-device,drive=disk0"

# -----------------------------------------------
# Multiboot partition scheme variable definitions
# -----------------------------------------------

WIC_DEVICE="vda"

# As qemu does not support booting into u-boot contained in the image, the bootloader will be provided externally.
# Instead of adding it to the partitioned image, we use the first partition for its environment and bootscripts.
WIC_BOOTLOADER_PART_SIZE = "16M"
WIC_BOOTLOADER_PART_CMD = "\
    /bootenv    --source extract-from-archive --sourceparams='file=qemu-bootloader-files.tar.gz' \
                --fstype=vfat --label bootenv --active --align 4096 --fixed-size ${WIC_BOOTLOADER_PART_SIZE}\
"
WIC_BOOTLOADER_CONFIG = "--ptable ${PTABLE_TYPE}"

# Unfortunately, we can't use the automatic image-based lookup provided by wic if we specify an exclude-path -
# therefore, we need to manually specify expected paths (which are stable though).
SYSTEM_IMAGE_ROOTFS_PATH = "${BASE_WORKDIR}/${MULTIMACH_TARGET_SYS}/${SYSTEM_IMAGE_NAME}/1.0/rootfs"
RECOVERY_IMAGE_ROOTFS_PATH = "${BASE_WORKDIR}/${MULTIMACH_TARGET_SYS}/${RECOVERY_IMAGE_NAME}/1.0/rootfs"

# Software partitions
WIC_FIRST_PARTITION_OFFSET = "" 
WIC_KERNELIMG_PART_SIZE = "50M"
WIC_KERNELIMG_SOURCE = "--source bootimg-partition"
WIC_RECOVERY_ROOTFS_PART_SIZE = "150M"
WIC_RECOVERY_ROOTFS_SOURCE = "--source rootfs --rootfs-dir ${RECOVERY_IMAGE_ROOTFS_PATH} --exclude-path boot/"
WIC_SYSTEM_ROOTFS_PART_SIZE = "400M"
WIC_SYSTEM_ROOTFS_SOURCE = "--source rootfs --rootfs-dir ${SYSTEM_IMAGE_ROOTFS_PATH} --exclude-path boot/"
WIC_APPFS_MIN_PART_SIZE = "100M"