#!/bin/bash
# Setup directory structure for the overlay system to guarantee a mount point

# System 
mkdir -p /var/persistent/overlay/etc       /var/persistent/overlay/etc-work
# User and application
mkdir -p /var/persistent/overlay/var/data  /var/persistent/overlay/var/data-work
# Update
mkdir -p /var/persistent/media